# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('user', encrypted_fields.fields.EncryptedCharField(max_length=150)),
                ('access_token', encrypted_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('groups', models.ManyToManyField(to='r_pass.Group')),
                ('hosts', models.ManyToManyField(to='r_pass.Host')),
            ],
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='r_pass.Service'),
        ),
    ]
