sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
before_script:
- pip install pep8
- pip install coverage
- pip install python-coveralls
- npm install jshint
- cp travis-ci/manage.py manage.py
script:
- pep8 r_pass/ --exclude=r_pass/tests
- jshint r_pass/static/js/main.js --verbose
- coverage run --source=r_pass/ --omit=r_pass/migrations/* manage.py test r_pass
after_success:
- coveralls
