sudo: false
language: python
dist: precise
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
before_script:
- pip install pep8
- pip install coverage
- pip install python-coveralls
- npm install jshint
- cp travis-ci/manage.py manage.py
- mkdir travis-ci/fieldkeys
- keyczart create --location=travis-ci/fieldkeys --purpose=crypt
- keyczart addkey --location=travis-ci/fieldkeys --status=primary --size=256
script:
- pep8 r_pass/ --exclude=migrations
- jshint r_pass/static/js/main.js --verbose
- coverage run --source=r_pass/ --omit=r_pass/migrations/* manage.py test r_pass
after_success:
- coveralls
